version: '{build}'
branches:
  only:
  - master
os: Visual Studio 2017
configuration: Release
platform: Any CPU
init:
- cmd: git config --global core.autocrlf true
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore source\WpfUtility.sln
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: QqOSIlkQnBg8ufQpEDSHBf3fLFTxtheoxy6Rs1px1ks0lB/1gcOxbAB54mjuxVV2
  artifact: /WpfUtility.*\.nupkg/
