version: '{build}'
branches:
  only:
  - master
os: Visual Studio 2015
configuration: Release
platform: Any CPU
init:
- cmd: git config --global core.autocrlf true
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore source\WpfUtility.sln
build:
  verbosity: minimal
